### ISSUE TITLE
latest release does not record any cassettes

### ISSUE THREAD

**Issue by darrenleeweber** [ktosiek/pytest-vcr#22]
## versions
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

$ poetry --version
Poetry 0.12.11

$ pip freeze | grep vcr
pytest-vcr==1.0.2
vcrpy==2.0.1

$ pip freeze | grep pytest
pytest==4.4.1
pytest-cov==2.7.1
pytest-forked==1.0.2
pytest-mock==1.10.4
pytest-ordering==0.6
pytest-runner==4.4
pytest-vcr==1.0.2
pytest-xdist==1.28.0
```

Removed all `tests/cassettes` and ran `pytest --vcr-record=all` to replace all the cassettes, but there's no output cassettes and all the tests that should record cassettes are passing.  There no custom configuration settings and tests use the basic `@pytest.mark.vcr()` decorators.

```
$ pytest --fixtures

----------------------------------------------------------------------------- fixtures defined from pytest_vcr ------------------------------------------------------------------------------
vcr_config
    Custom configuration for VCR.py
vcr
    The VCR instance
vcr_cassette
    Wrap a test in a VCR.py cassette
vcr_cassette_dir
    .venv/lib/python3.7/site-packages/pytest_vcr.py:92: no docstring available
vcr_cassette_name
    Name of the VCR cassette
```

**Comment by ktosiek** [comment]
Thank you for the report! Which version are you upgrading from?

**Comment by darrenleeweber** [comment]
Prior working versions might have been (from git commit on Pipfile.lock):
```
pytest==4.02
pytest-vcr==1.0.1
vcrpy==2.0.1
```

**Comment by ktosiek** [comment]
That is strange, especially if downgrade did not help. Do you use unittest.TestCase? Can you:
- extract a small example of a test that fails to generate a cassette?
- make sure the tests actually run, by putting a failing assertion after the code that should get recorded by VCR?

**Comment by darrenleeweber** [comment]
```python
# all the library imports are good, plus:
import pytest

@pytest.mark.vcr()
def test_fetch_json_with_site_string(dates):
    site = "01115183"
    q = USGSClient.query(site, dt_start=dates.begin, dt_end=dates.end, data_format='json')
    response = USGSClient.fetch(q)
    check_json_response(response)
```

```
$ pytest --vcr-record=all tests/test_usgs_fetch.py -k 'test_fetch_json_with_site_string'
============ test session starts ====================
platform linux -- Python 3.7.2, pytest-4.0.2, py-1.8.0, pluggy-0.9.0
rootdir: /home/joe/src/jupiter/usgs-water-services, inifile: pytest.ini
plugins: requests-mock-1.6.0, xdist-1.27.0, vcr-1.0.1, ordering-0.6, mock-1.10.4, forked-1.0.2, cov-2.7.1
collected 6 items / 5 deselected                                                                                                                                                            

tests/test_usgs_fetch.py .                                                                                                                                                            [100%]
```

```
$ cat pytest.ini 
[pytest]
log_format = %(asctime)s - %(name)-12s - %(levelname)-8s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S

filterwarnings =
    module::DeprecationWarning
```
With or without that `pytest.ini` file, the behavior is the same.  The `tests/cassettes` directory is the same before/after, i.e.
```
tests/
├── cassettes
```

**Comment by darrenleeweber** [comment]
```toml
# pyproject.toml snippets

[tool.poetry.dependencies]
python = "^3.7"
lxml = "^4.3"
numpy = "*"
OWSLib = "^0.17.0"
pandas = "^0.24.0"
pytz = "*"
pyyaml = "*"
requests = "^2.0"
scipy = "*"
urllib3 = "*"

[tool.poetry.dev-dependencies]
alabaster = "*"
black = {version = "^18.3-alpha.0", allows-prereleases = true}
codecov = "*"
docutils = "*"
"flake8" = "*"
"flake8-type-annotations" = "*"
freezegun = "*"
ipdb = "*"
ipython = "*"
invoke = "*"
invoke-release = "*"
pylint = "^2.3"
pytest = "^4.0"
pytest-cov = "*"
pytest-mock = "*"
pytest-ordering = "*"
pytest-runner = "*"
pytest-vcr = "*"
pytest-xdist = "*"
requests_mock = "*"
sphinx = "^2.0"
tox = "*"
detox = "*"
twine = "^1.0"
yapf = "*"
wheel = "*"
```
